### ISSUE TITLE
User profile nav scroll

### ISSUE THREAD

**Issue by arathjz** [debtcollective/discourse-debtcollective-theme#90]
**What:**
There's an unexpected scroll behavior on the navbar at the user profile
![image](https://user-images.githubusercontent.com/20747535/89954356-864f4080-dbf6-11ea-8486-0b69b7c1d681.png)

**Why:**
Seems like the issue is related to this style rule

```css
user-nav {
    overflow-x: scroll;
    min-height: 3rem;
}
```

**Solution:**
This could be fixed by setting user nav overflow as hidden
